### ISSUE TITLE
NameError: name 'treecore' is not defined

### ISSUE THREAD

**Issue by hmatsu1226** [balabanmetin/apples#8]
I had following error message in running apples, and the calculation did not appear to be progressing.
I use python 3.8.1 on macOS Catalina.
I hope you will be able to provide the information.

 % run_apples.py -d data/small_dist.mat -t data/small_backbone.nwk
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/matsumoto/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/matsumoto/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/matsumoto/.pyenv/versions/3.8.1/bin/run_apples.py", line 26, in runquery
    for l in treecore.tree.traverse_postorder(internal=False):
NameError: name 'treecore' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matsumoto/.pyenv/versions/3.8.1/bin/run_apples.py", line 159, in <module>
    results = pool.starmap(runquery, queries)
  File "/Users/matsumoto/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/matsumoto/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
NameError: name 'treecore' is not defined

**Comment by balabanmetin** [comment]
Python 3.8 broke APPLES. I made necessary changes and it should work now. Please upgrade your APPLES version to 1.3.0 by running the following command:

`pip3 install --upgrade apples`

or cloning the newest version from github.

**Comment by hmatsu1226** [comment]
Thank you for your quick response.
